### ISSUE TITLE
Errors running the code

### ISSUE THREAD

**Issue by eibragimova** [Seeed-Studio/Accelerometer_ADXL345#1]
Dear all,

when I upload the code, I get these errors in the arduino:

ADXL345_demo_code.ino: In function 'void loop()':
ADXL345_demo_code:87: error: 'class ADXL345' has no member named 'readXYZ'
ADXL345_demo_code:98: error: 'class ADXL345' has no member named 'getAcceleration'

Has anyone had the same problem or does anyone know of a solution? (kind of a newbie here :)

**Comment by reeedstudio** [comment]
Hi, I try the code and it's nothing wrong, may I ask did you put this library to libraries folder to you Arduino?  just like this ： ....\arduino-1.0.5\libraries
