### ISSUE TITLE
how to calibrate ADXL354

### ISSUE THREAD

**Issue by tonyvr4** [Seeed-Studio/Accelerometer_ADXL345#11]
Is there a method in this library to calibrate the ADXL3545?

The library reads values but the numbers never settle to zero even if the device is taped to the desk

**Comment by Pillar1989** [comment]
Please help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seeed-Studio/Accelerometer_ADXL345"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 晚上10:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Seeed-Studio/Accelerometer_ADXL345] how to calibrate ADXL354 (#11)





 
Is there a method in this library to calibrate the ADXL3545?
 
The library reads values but the numbers never settle to zero even if the device is taped to the desk

**Comment by haiershu** [comment]
Hi there，
I don't have the library to calibrate the ADXL3545, But I may know the reason for the abnormal data.
After continuous breakpoint tracking, I found that when the vibration value is large, there will be several singular values in the collected data. For example, when the sensor is stationary, the normal data is generally around 250, but occasionally one or two zeros or a value of 500 will pop up. These two singular values are in an array, and after FFT transformation, a small vibration value will be displayed at many frequencies.
I guess the data protection is not good, the single-chip to read the FIFO and the chip to write the FIFO affect each other.
This is a chip problem, and there is no good way to completely solve it, although you can try to average out readings by using the average of multiple measurements to reduce the error.

**Comment by facukolo** [comment]
Prueba que tal si haces X*(16/255) si estas en rango 16, sino cambia por 8, 4, o 2. Son valores de salida de un ADC.

**Comment by ackPeng** [comment]
Does this problem still exist? If calibration is not possible, you can try using some filtering algorithms (such as Kalman filtering, etc.) to solve this problem.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
