### ISSUE TITLE
Getting only values of zero

### ISSUE THREAD

**Issue by ashishdatta** [Seeed-Studio/Accelerometer_ADXL345#2]
Hi I am using an Intel Edison board and I am currently only getting values of zero for X, Y, and Z ... the code compiles fine, any suggestions to fix this?

**Comment by KillingJacky** [comment]
Dear dev,

Edison supports limited sensors, please find out here: https://github.com/intel-iot-devkit/upm/

**Comment by ashishdatta** [comment]
But I am using the Arduino code from here :/ what does the UPM repo mean in this context?

So I found one issue, I was using 5v instead of 3v3 on the grove shield, but now I am getting large and negative values. I think I getting an overflow somewhere.
