### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/Accelerometer_ADXL345#5]
The Wire.endTransmission() and Wire.beginTransmission() should not be used together with Wire.requestFrom().

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.

**Comment by KillingJacky** [comment]
Hi @Koepel , indeed mistakes, thank you.

**Comment by KillingJacky** [comment]
Same here: https://github.com/Seeed-Studio/Grove_3_Axis_Compass_V2.0_BMM150/issues/3

**Comment by lanselambor** [comment]
Thank you, have corrected the mistakes.
