### ISSUE TITLE
Difficulties connecting the device.

### ISSUE THREAD

**Issue by dpaetsch** [Seeed-Studio/Accelerometer_ADXL345#8]
Greetings, 
I'm having a little trouble with the code you posted, I have included both wire and adxl libraries and have them installed on the arduino program and have copied and pasted your code but an error code keeps popping up when I declare adxl as a variable ADXL.
The error message says "no matching function for call to 'ADXL345::ADXL345()' "
Thank you for your time, it would mean a lot if someone helped me out

**Comment by Pillar1989** [comment]
Is there any update on this issue? No problem was found in our test

**Comment by facukolo** [comment]
Hola, la solución es que en la misma carpeta donde está el archivo demo, copien el ADXL345.cpp y .h. De ese modo, cuando ejecuten la IDE de Arduino deben aparecer esas dos pestañas en la ventana. Por último, cambien #include <ADXL345.h> por #include "ADXL345.h".

**Comment by Pardova** [comment]
Got it, thanks for your help.

Wang

facukolo ***@***.***> 於 2023年5月18日 週四 下午1:14寫道：

**Comment by ackPeng** [comment]
Does this problem still exist now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
